// Generated by Wrangler by running `wrangler types`

interface Env {
  VALUE_FROM_CLOUDFLARE: 'Hello from Cloudflare'
  SESSION_SECRET: string
  GOOGLE_CLIENT_ID: string
  GOOGLE_CLIENT_SECRET: string
  GOOGLE_REDIRECT_URI: string
  DB: D1Database
}
