workers_dev = true
name = "owndr-worker"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]
main = "./build/server/index.js"
assets = { directory = "./build/client/" }

[vars]
VALUE_FROM_CLOUDFLARE = "Hello from Cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "owndr"
database_id = "682da9b9-584c-4c5d-afce-4c6823e605e3"
migrations_dir = "db/migrate"
